export default {
  tabs: [],
  active: null,
  files: [],
  variables: [],
  commands: [],
  cmdIndex: 0,
  engine: {},
  lastJob: null,
  activeOutput: null,
  figureIndex: 0,
  figureURLs: [],
  figureData: [],
  figures: [],
  lastFiguresKey: "",
  plotMode: "interactive",
  interactivePlot: null,
  draftTimer: undefined,
  toastTimer: undefined,
  polling: false,
  publishRenders: new Map(),
  mathJaxPromise: null,
  currentFolder: "",
  folderRoot: "",
  defaultWorkspace: "",
  folderHistory: [],
  folderIndex: -1,
  listingTruncated: false,
  draftScope: "",
  busy: false,
  starting: true,
  lastEpoch: null,
  wasDisconnected: false,
  uiGeneration: 0,
  lintSequence: 0,
  breakpointKey: "",
  debugPanelKey: "",
  debugSnapshotKey: "",
  breakpoints: new Map(),
  editor: undefined,
  editorFontSize: undefined,
  commandCompletion: null,
  commandRecall: null,
  historyEntries: [],
  historySession: "",
  settings: undefined
};
