const {chromium}=require('@playwright/test');
const fs=require('fs'),path=require('path'),assert=require('assert');
const {randomUUID,createHash}=require('node:crypto');
const navFolder=path.resolve('workspace/ui-nav-folder');
// A failed run can leave its saved source behind; never overwrite that file.
const uiStem='ui_test_'+randomUUID().replaceAll('-',''),uiName=uiStem+'.m',uiPath=path.resolve('workspace',uiName),uiReportPath=path.resolve('workspace/html',uiStem+'.html');
const uiFigureTag='publish-fixture-'+uiStem;
const equationFixture=String.raw`%% UI denklemleri $x^2$
%
% $$e^{i\pi}+1=0$$
%
% <https://example.org Example link> and |$code$|.
answer = 144;
disp(answer);
disp('$output$');
ui_report_figures = findall(0,'type','figure');
ui_report_figure = max([0; ui_report_figures(:)]) + 1;
figure(ui_report_figure,'tag','${uiFigureTag}'); plot(1:3,[1 4 9]); title('Yayın görseli');
`;
(async()=>{
 const launch=JSON.parse(fs.readFileSync('.matlab-free/launch.json','utf8'));
 fs.mkdirSync(navFolder,{recursive:true});fs.writeFileSync(path.join(navFolder,'nav_run.m'),'folder_answer = 321;\ndisp(folder_answer);\n');fs.writeFileSync('workspace/ui_debug_test.m','debug_a=1;\ndebug_b=debug_a+2;\ndebug_done=debug_b*3;\n');
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({ locale: "tr-TR",viewport:{width:1512,height:982},deviceScaleFactor:1});
 let executeCount=0,mathJaxRequests=0;page.on('request',r=>{if(r.url().endsWith('/api/execute'))executeCount++;if(r.url().endsWith('/mathjax-tex-svg.js'))mathJaxRequests++;});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
 {const [base,token]=launch.url.split('#');const req=(p,o={})=>fetch(base+p,{...o,headers:{'X-MF-Token':token,'Content-Type':'application/json',...(o.headers||{})}});
  for(let i=0;i<200&&(await (await req('api/state')).json()).status!=='idle';i++)await new Promise(r=>setTimeout(r,100));
  await req('api/execute',{method:'POST',body:JSON.stringify({mode:'code',code:'ui_history_a=1;\nui_history_b=2;',history:true})});
  for(let i=0;i<200&&(await (await req('api/state')).json()).status!=='idle';i++)await new Promise(r=>setTimeout(r,100));}
 await page.goto(launch.url);await page.waitForLoadState('domcontentloaded');
 await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır').catch(async e=>{console.log(await page.locator('body').innerText());await page.screenshot({path:'docs/ui-failure.png'});throw e;});
 assert((await page.locator('.cm-content').innerText()).includes("IndyMAT'e hoş geldin"));
 await page.waitForFunction(()=>document.querySelectorAll('.cm-foldGutter span').length>0);
 const multilineHistory=page.locator('.history-item').first();assert((await multilineHistory.innerText()).includes('\n'));assert.equal(await multilineHistory.evaluate(n=>getComputedStyle(n).whiteSpace),'pre-wrap');assert((await multilineHistory.boundingBox()).height>24);
 assert.equal(await page.locator('body').evaluate(n=>getComputedStyle(n).color),'rgb(224, 224, 224)','fresh context defaults to dark');
 assert.equal(await page.evaluate(()=>localStorage.getItem('mf-theme')),'dark');
 await page.screenshot({path:'docs/ui-initial.png',fullPage:true});
 await page.locator('#command').fill('doc fft');await page.locator('#command').press('Enter');await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='fft — Yardım'&&document.querySelector('#modal-body').innerText.includes('Octave çekirdeği'));await page.locator('#modal-close').click();
 await page.getByRole('button',{name:'Paketler',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.package-list')?.innerText.includes('signal'));assert((await page.locator('.package-list').innerText()).includes('Bu oturumda yüklü'));await page.locator('#modal-close').click();
 await page.getByRole('button',{name:'ui_debug_test.m',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#editor-label').textContent==='ui_debug_test.m');
 await page.locator('.cm-breakpoint-gutter .cm-gutterElement').nth(1).click();await page.waitForSelector('.cm-breakpoint-marker');await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
 assert(!(await page.locator('#debug-controls').isVisible()),'debug controls visible while not paused');
 await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Kesme noktasında'&&document.querySelector('#variables').innerText.includes('debug_a'));assert.equal(await page.locator('.cm-debug-line').count(),1);assert.equal(await page.locator('#editor-label').innerText(),'ui_debug_test.m');
 await page.locator('#debug-controls [data-debug="step"]').click();await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Kesme noktasında'&&document.querySelector('.cm-debug-line')?.textContent.includes('debug_done'));
 await page.locator('#debug-controls [data-debug="continue"]').click();await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#variables').innerText.includes('debug_done'));assert(!(await page.locator('#debug-controls').isVisible()),'debug controls still visible after continue');
 await page.locator('.cm-breakpoint-gutter .cm-gutterElement').nth(1).click();await page.waitForFunction(()=>!document.querySelector('.cm-breakpoint-marker')&&document.querySelector('#status-text').textContent==='Hazır');await page.locator('.editor-tab').filter({hasText:'hosgeldin.m'}).click();
 await page.locator('#run').click();
 await page.waitForFunction(()=>document.querySelector('#variables').children.length>5,{},{timeout:30000});
 await page.waitForFunction(()=>document.querySelector('#plot-area canvas')||document.querySelector('#plot-area img')?.naturalWidth>0);
 assert((await page.locator('#console').innerText()).includes('1000'));
 await page.screenshot({path:'docs/ui-working.png',fullPage:true});
 await page.locator('#command').fill("close all; figure(77); plot([1 2 3],[10 20 15],'-o','color','none','markeredgecolor',[0 0 0],'markerfacecolor',[0 .5 .7],'displayname','ölçüm'); legend('show');");await page.locator('#command').press('Enter');await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&Array.from(document.querySelectorAll('#figure-tabs button')).some(b=>b.textContent==='Figure 77')&&document.querySelector('#plot-area canvas'));
 const canvas=page.locator('#plot-area canvas'),initialView=await canvas.getAttribute('data-view'),plotState=await page.evaluate(async()=>{let token=sessionStorage.getItem('mf-token'),state=await (await fetch('/api/state',{headers:{'X-MF-Token':token}})).json(),figure=state.figures[0],data=await (await fetch(`/api/figure?job=${figure.job}&file=${figure.data_file}`,{headers:{'X-MF-Token':token}})).json();return data;});
 assert.equal(plotState.version,2);assert.equal(plotState.axes[0].series[0].line_color,'none');assert.deepStrictEqual(plotState.axes[0].series[0].marker_edge_color,[0,0,0]);assert.deepStrictEqual(plotState.axes[0].series[0].marker_face_color,[0,.5,.7]);
 let axis=plotState.axes[0],box=await canvas.boundingBox(),position=axis.position,x=box.x+(position[0]+.5*position[2])*box.width,y=box.y+(1-position[1]-position[3]+0*position[3])*box.height;await page.mouse.move(x,y);await page.waitForSelector('.plot-data-tip:not([hidden])');let tip=await page.locator('.plot-data-tip').innerText();assert(tip.includes('ölçüm'));assert(tip.includes('x = 2'));assert(tip.includes('y = 20'));
 await page.mouse.move(box.x+(position[0]+.2*position[2])*box.width,box.y+(1-position[1]-.8*position[3])*box.height);await page.mouse.down();await page.mouse.move(box.x+(position[0]+.8*position[2])*box.width,box.y+(1-position[1]-.2*position[3])*box.height);await page.mouse.up();assert.notEqual(await canvas.getAttribute('data-view'),initialView);await canvas.dblclick();assert.equal(await canvas.getAttribute('data-view'),initialView);
 await page.locator('#plot-png').click();await page.waitForFunction(()=>document.querySelector('#plot-area img')?.naturalWidth>0);await page.locator('#plot-interactive').click();await page.waitForSelector('#plot-area canvas');
 await page.locator('#command').fill('test_result = 6*7; size_probe = magic(3); disp(test_result)');await page.locator('#command').press('Enter');
 await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#variables').innerText.includes('test_result')&&document.querySelector('#variables').innerText.includes('size_probe'));
 const resultCell=page.getByRole('cell',{name:'test_result',exact:true});assert.equal(await resultCell.locator('xpath=..').locator('td').nth(2).innerText(),'1×1');
 assert.equal(await page.getByRole('cell',{name:'size_probe',exact:true}).locator('xpath=..').locator('td').nth(2).innerText(),'3×3');
 await page.locator('#command').fill('mag');await page.locator('#command').press('Tab');assert.equal(await page.locator('#command').inputValue(),'magic');await page.locator('#command').fill('test_re');await page.locator('#command').press('Tab');assert.equal(await page.locator('#command').inputValue(),'test_result');await page.locator('#command').fill('');
 await resultCell.dblclick();
 await page.waitForSelector('#modal[open]');assert((await page.locator('#modal-body').innerText()).includes('42'));await page.locator('#modal-close').click();
 await page.locator('[data-action="new"]').first().click();
 await page.locator('.cm-content').fill('fft');await page.locator('.cm-line').click();await page.keyboard.press('Home');await page.keyboard.press('F1');await page.waitForFunction(()=>document.querySelector('#modal-title').textContent==='fft — Yardım'&&document.querySelector('#modal-body').innerText.includes('Octave çekirdeği'));await page.locator('#modal-close').click();
 await page.locator('.cm-content').fill('x = ;');await page.waitForFunction(()=>document.querySelector('#code-issues').textContent==='1 sözdizimi hatası, satır 1');await page.waitForSelector('.cm-lint-marker-error');assert(await page.locator('.cm-lintRange-error').count());await page.locator('.cm-lintRange-error').hover();await page.waitForSelector('.cm-tooltip-lint');assert((await page.locator('.cm-tooltip-lint').innerText()).includes('Sözdizimi hatası'));
 await page.locator('.cm-content').fill(equationFixture);
 await page.waitForFunction(()=>document.querySelector('#code-issues').textContent==='Sorun yok');
 await page.locator('[data-action="save"]').first().click();
 await page.getByLabel('Dosya adı').fill(uiName);
 const savedResponsePromise=page.waitForResponse(r=>r.url().endsWith('/api/file')&&r.request().method()==='POST'&&r.request().postDataJSON().path===uiPath);
 await page.locator('.save-dialog button').click();
 const savedResponse=await savedResponsePromise,savedBody=await savedResponse.json();assert.equal(savedResponse.status(),200,JSON.stringify(savedBody));assert.equal(savedResponse.request().postDataJSON().hash,'absent');
 await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='Kaydedildi');
 assert.equal(fs.readFileSync(uiPath,'utf8'),equationFixture);assert.equal(createHash('sha256').update(fs.readFileSync(uiPath)).digest('hex'),savedBody.hash);
 const previousCount=executeCount;await page.locator('.cm-content').click();await page.keyboard.press('F5');
 await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#variables').innerText.includes('answer'));assert.equal(executeCount,previousCount+1,'F5 executed twice');
 await page.locator('.run-more summary').click();await page.locator('#run-profile').click();await page.waitForFunction(()=>document.querySelector('#modal[open] #modal-title')?.textContent==='Profil sonuçları');assert((await page.locator('.profile-table').innerText()).includes(uiStem));assert((await page.locator('.profile-table').innerText()).includes('Çağrı'));await page.getByRole('button',{name:'Çağrı sütununu sırala'}).click();await page.locator('.profile-table tr').filter({hasText:uiStem}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open&&document.querySelector('#cursor').textContent.startsWith('Satır 1,'));
 // Run/profile must leave the saved source bytes (and therefore its hash) intact.
 // Octave publish captures handles absent from its initial snapshot, not
 // changed existing figures. Choose max(open handles)+1 on EVERY execution:
 // Run/Profile also execute this file, so even a fixed reserved ID is unsafe.
 assert.equal(createHash('sha256').update(fs.readFileSync(uiPath)).digest('hex'),savedBody.hash,'run/profile changed the saved source');assert.equal(await page.locator('#editor-label').innerText(),uiName);assert.equal(mathJaxRequests,0,'MathJax was not lazy');
 await page.locator('.run-more summary').click();await page.locator('#publish').click();await page.waitForFunction(()=>document.querySelector('#modal[open] #modal-title')?.textContent==='Yayın raporu');await page.waitForSelector('.publish-frame');assert.equal(mathJaxRequests,1);assert.equal(await page.getByRole('button',{name:'HTML indir'}).count(),1);assert((await page.locator('.publish-actions').innerText()).includes(uiStem+'.html'));
 let savedReport=fs.readFileSync(uiReportPath,'utf8');assert.equal((savedReport.match(/<svg\b/gi)||[]).length,2);assert(savedReport.includes('aria-label="$x^2$"'));assert(savedReport.includes('<title>$x^2$</title>'));assert(savedReport.includes(String.raw`aria-label="$$e^{i\pi}+1=0$$"`));assert(!/<(?:script|mjx-assistive-mml|math)\b/i.test(savedReport));assert(savedReport.includes('href="https://www.octave.org"'));for(let literal of ['$code$','$output$'])assert(!savedReport.includes('aria-label="'+literal+'"'),'literal code/output was typeset');assert(!/mathjax-tex-svg\.js/i.test(savedReport));assert.equal(createHash('sha256').update(fs.readFileSync(uiPath)).digest('hex'),savedBody.hash,'publish changed the saved source');
 const reportFrame=page.frameLocator('.publish-frame');await reportFrame.locator('h2 a#node1 svg').waitFor();assert.equal(await reportFrame.locator('a[href="#node1"]').innerText(),'UI denklemleri $x^2$');assert.equal(await reportFrame.locator('a[href="https://example.org"]').innerText(),'Example link');assert.equal(await reportFrame.locator('a[href] svg').count(),0);assert.equal(await reportFrame.locator('code').innerText(),'$code$');assert((await reportFrame.locator('.oct-code-output').innerText()).includes('$output$'));
 const mathLayout=await reportFrame.locator('mjx-container').evaluateAll(nodes=>nodes.map(n=>{let svg=n.querySelector('svg'),box=svg.getBoundingClientRect();return {display:getComputedStyle(n).display,align:getComputedStyle(n).textAlign,overflow:getComputedStyle(svg).overflow,verticalAlign:svg.style.verticalAlign,hidden:svg.getAttribute('aria-hidden'),width:box.width,height:box.height};}));assert.deepStrictEqual(mathLayout.map(n=>n.display),['inline-block','block']);assert.equal(mathLayout[1].align,'center');for(let math of mathLayout){assert.equal(math.overflow,'visible');assert(math.verticalAlign);assert.equal(math.hidden,null);assert(math.width>0&&math.height>0);}
 const publishState=await page.evaluate(async()=>await (await fetch('/api/state',{headers:{'X-MF-Token':sessionStorage.getItem('mf-token')}})).json());assert.equal(publishState.publish.staged,false);assert.equal(publishState.publish.images,1);assert((await page.locator('.publish-actions').innerText()).includes('1 görsel'));assert(!fs.existsSync(path.join('.matlab-free','jobs',publishState.job,'publish')));
 assert(savedReport.includes('src="data:image/png;base64,'));assert(savedReport.includes('Content-Security-Policy'));assert.equal(await page.locator('.publish-frame').getAttribute('sandbox'),'');assert.equal(await reportFrame.locator('img').count(),1);await reportFrame.locator('img').evaluate(img=>img.decode());assert(await reportFrame.locator('img').evaluate(img=>img.naturalWidth>0&&img.naturalHeight>0));
 assert((await reportFrame.locator('head > meta').first().getAttribute('content')).includes("img-src data:"));
 const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'Yeni sekmede aç',exact:true}).click();const popup=await popupPromise;await popup.frameLocator('iframe').locator('h2 a#node1 svg').waitFor();assert.equal(await popup.locator('iframe').getAttribute('sandbox'),'');assert(await popup.evaluate(()=>window.opener===null));await popup.frameLocator('iframe').locator('img').evaluate(img=>img.decode());await popup.close();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'HTML indir',exact:true}).click();const downloaded=await downloadPromise;assert.equal(downloaded.suggestedFilename(),uiStem+'.html');const downloadedHtml=fs.readFileSync(await downloaded.path(),'utf8');assert.equal((downloadedHtml.match(/<svg\b/g)||[]).length,2);assert(downloadedHtml.includes('src="data:image/png;base64,'));assert(downloadedHtml.includes('Content-Security-Policy'));assert(!/<script\b/i.test(downloadedHtml));await page.locator('#modal-close').click();
 const resources=await page.evaluate(html=>{let doc=new DOMParser().parseFromString(html,'text/html');return [...doc.querySelectorAll('[src],[srcset],[poster],link[href],svg image,svg use,object[data],form[action]')].flatMap(node=>[...node.attributes].filter(attr=>['src','srcset','poster','href','xlink:href','data','action'].includes(attr.name)&&/^\s*(?:https?:)?\/\//i.test(attr.value)).map(attr=>node.localName+' '+attr.name+'='+attr.value));},savedReport);assert.deepStrictEqual(resources,[]);
 // Publish deletes its newly captured figure. Clean up only this fixture's
 // remaining Run/Profile figures; keep unrelated session figures untouched.
 await page.locator('#command').fill(`close(findall(0,'type','figure','tag','${uiFigureTag}')); assert(isempty(findall(0,'type','figure','tag','${uiFigureTag}'))); disp('ui_publish_figures_closed');`);await page.locator('#command').press('Enter');
 await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&/\nui_publish_figures_closed\n/.test(document.querySelector('#console').innerText));
 const historyBeforeSection=await page.evaluate(async()=>{let token=sessionStorage.getItem('mf-token');return (await (await fetch('/api/history',{headers:{'X-MF-Token':token}})).json()).length;});
 await page.locator('.cm-content').fill('function y = fold_test(x)\nif x\ny = 1;\nend\nfor k = 1:2\ny = y + k;\nend\nwhile y < 5\ny++;\nend\nswitch y\ncase 5\ny = 6;\nend\nend');await page.waitForFunction(()=>document.querySelectorAll('.cm-foldGutter span').length>=5);
 await page.locator('.cm-content').fill('%% UI bölümü\nsection_history_probe = 314159;\ndisp(section_history_probe);\n%% Sonraki bölüm\nother_probe = 2;');await page.locator('.cm-line').first().click();await page.locator('#run-section').click();
 await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#variables').innerText.includes('section_history_probe'));
 const sectionCommand=page.locator('.console-command').last();assert.equal(await sectionCommand.innerText(),`>> Bölüm · ${uiName}:1–3`);assert((await sectionCommand.getAttribute('title')).includes('section_history_probe = 314159;'));assert(!(await sectionCommand.innerText()).includes('314159'));
 await page.locator('.cm-line').nth(1).click();await page.keyboard.press('Home');await page.keyboard.down('Shift');await page.keyboard.press('End');await page.keyboard.up('Shift');await page.locator('#run-selection').click();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('.console-command')).at(-1)?.textContent==='>> Seçim · 1 satır');await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
 const historyAfterSection=await page.evaluate(async()=>{let token=sessionStorage.getItem('mf-token');return await (await fetch('/api/history',{headers:{'X-MF-Token':token}})).json();});assert.equal(historyAfterSection.length,historyBeforeSection);assert(!historyAfterSection.some(v=>v.includes('section_history_probe')));
 await page.locator('.cm-content').click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.insertText('\nundo_probe = 1;');await page.getByRole('button',{name:'Geri al'}).click();assert(!(await page.locator('.cm-content').innerText()).includes('undo_probe'));await page.getByRole('button',{name:'Yinele'}).click();assert((await page.locator('.cm-content').innerText()).includes('undo_probe'));
 const tabCount=await page.getByRole('tab').count();await page.locator('#new-tab').click();assert.equal(await page.getByRole('tab').count(),tabCount+1);assert((await page.locator('#editor-label').innerText()).startsWith('yeni_'));
 await page.keyboard.press('ControlOrMeta+p');await page.getByLabel('Dosyaya git').fill(uiName);await page.getByLabel('Dosyaya git').press('Enter');await page.waitForFunction(name=>document.querySelector('#editor-label').textContent===name,uiName);
 await page.locator('.cm-content').click();await page.keyboard.press('ControlOrMeta+=');assert.equal(await page.evaluate(()=>localStorage.getItem('mf-editor-font-size')),'14');assert.equal(await page.locator('.cm-editor').evaluate(n=>getComputedStyle(n).fontSize),'14px');
 await page.locator('#command').fill('while true; end');await page.locator('#command').press('Enter');
 await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hesaplanıyor');
 await page.locator('#command').fill('kopyalanacak');await page.locator('#command').selectText();await page.locator('#command').press('Control+c');await page.waitForTimeout(300);assert.equal(await page.locator('#status-text').innerText(),'Hesaplanıyor');await page.locator('#command').press('End');await page.locator('#command').press('Control+c');await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır',{}, {timeout:10000});
 await page.locator('#command').fill("ui_input=input('Ad: ','s');");await page.locator('#command').press('Enter');await page.waitForSelector('#input-bar:not([hidden])');await page.locator('#runtime-input').fill('Osman');await page.locator('#send-input').click();await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#variables').innerText.includes('Osman'));
 await page.locator('#command').fill("disp('clc-oncesi-ui'); clc; disp('clc-sonrasi-ui');");await page.locator('#command').press('Enter');await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#console').innerText.includes('clc-sonrasi-ui'));assert(!(await page.locator('#console').innerText()).includes('clc-oncesi-ui'));assert(!(await page.locator('#console').innerText()).includes('__MF_CLC_'));assert(!(await page.locator('#console').innerText()).includes('1000'));
 await page.locator('[data-action="save-as"]').click();await page.getByLabel('Dosya adı').fill('ui_copy_test.m');await page.locator('.save-dialog button').click();await page.waitForFunction(()=>document.querySelector('#editor-label').textContent==='ui_copy_test.m');assert(fs.existsSync('workspace/ui_copy_test.m'));fs.unlinkSync('workspace/ui_copy_test.m');
 await page.locator('.file-button.folder').filter({hasText:'ui-nav-folder'}).click();await page.waitForFunction(folder=>document.querySelector('#folder-address').title===folder,navFolder);await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
 await page.getByRole('button',{name:'nav_run.m',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#editor-label').textContent==='nav_run.m');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#variables').innerText.includes('folder_answer'));
 await page.locator('[data-action="new"]').first().click();await page.locator('.cm-content').fill('yalniz_taslak = 7;');await page.waitForTimeout(300);let scoped=await page.evaluate(()=>JSON.parse(localStorage.getItem('mf-drafts-v2')));assert(Object.values(scoped.scopes).some(scope=>scope.tabs.some(tab=>tab.dirty&&tab.path.startsWith(navFolder+'/'))));
 await page.locator('#folder-back').click();await page.waitForFunction(folder=>document.querySelector('#folder-address').title===folder,path.resolve('workspace'));await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
 await page.locator('#command').fill(`cd('${navFolder}')`);await page.locator('#command').press('Enter');await page.waitForFunction(folder=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#folder-address').title===folder,navFolder);await page.locator('#folder-up').click();await page.waitForFunction(folder=>document.querySelector('#status-text').textContent==='Hazır'&&document.querySelector('#folder-address').title===folder,path.resolve('workspace'));
 assert.equal(await page.locator('body').evaluate(n=>getComputedStyle(n).color),'rgb(224, 224, 224)');await page.screenshot({path:'docs/ui-dark.png',fullPage:true});
 await page.locator('#theme').click();assert.equal(await page.locator('body').evaluate(n=>getComputedStyle(n).color),'rgb(17, 26, 50)');assert.equal(await page.evaluate(()=>localStorage.getItem('mf-theme')),'light');await page.screenshot({path:'docs/ui-light.png',fullPage:true});
 await page.locator('#theme').click();assert.equal(await page.locator('body').evaluate(n=>getComputedStyle(n).color),'rgb(224, 224, 224)');assert.equal(await page.evaluate(()=>localStorage.getItem('mf-theme')),'dark');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/ui-mobile.png',fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow');
 await page.locator('#toggle-files').click();assert(await page.locator('#left-panel').isVisible());
 assert.deepStrictEqual(errors,[]);
 fs.unlinkSync(uiPath);fs.unlinkSync('workspace/ui_debug_test.m');fs.rmSync(uiReportPath,{force:true});try{fs.rmdirSync('workspace/html');}catch{}
 await page.reload();await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');assert.equal(await page.locator('.cm-editor').evaluate(n=>getComputedStyle(n).fontSize),'14px','editor font size did not persist across reload');
 const fresh=await browser.newPage({ locale: "tr-TR" });await fresh.route('**/api/file?path=examples%2Fhosgeldin.m',route=>route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:'missing'})}));await fresh.goto(launch.url);await fresh.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');assert(await fresh.locator('#command').isEnabled());
 const legacyContext=await browser.newContext({ locale: "tr-TR" });const legacy=await legacyContext.newPage();await legacy.goto(launch.url);await legacy.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');const legacyRaw=JSON.stringify({tabs:[{path:'legacy_draft.m',content:'legacy_value=9;',saved:'',hash:null,dirty:true}],active:'legacy_draft.m'});await legacy.evaluate(raw=>{localStorage.removeItem('mf-drafts-v2');localStorage.setItem('mf-drafts',raw);},legacyRaw);await legacy.reload();await legacy.waitForFunction(()=>document.querySelector('#editor-label').textContent==='legacy_draft.m');let migration=await legacy.evaluate(()=>({old:localStorage.getItem('mf-drafts'),next:JSON.parse(localStorage.getItem('mf-drafts-v2'))}));assert.equal(migration.old,legacyRaw);assert(Object.values(migration.next.scopes).some(scope=>scope.tabs.some(tab=>tab.path.endsWith('/workspace/legacy_draft.m')&&tab.dirty)));await legacyContext.close();
 await browser.close();fs.rmSync(navFolder,{recursive:true});console.log('UI PASS: current-folder navigation/run, scoped draft migration, editor lint, clc, folding, graph, command completion/history, workspace size, editor tabs/undo/quick open/font, section labels, interrupt, dark mode, mobile.');
})().catch(e=>{try{fs.rmSync(navFolder,{recursive:true});}catch{}try{fs.unlinkSync('workspace/ui_debug_test.m');}catch{}console.error(e);process.exit(1);});
