const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const { assistantServer } = require('./assistant_harness.cjs');
(async () => {
  const server = await assistantServer();
  let browser;
  try {
    browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ locale: 'tr-TR' });
    const page = await context.newPage();
    await page.goto(server.launch.url);
    await page.locator('#files .file-button').filter({ hasText: 'sample' }).click();
    await page.locator('.cm-line').first().click();
    await page.locator('#toggle-assistant').click();
    await page.waitForFunction(() => [...document.querySelector('#assistant-provider').options].every((option) => !option.disabled));
    assert.equal(await page.locator('#assistant-mode').inputValue(), 'ask');
    assert.equal(await page.locator('#assistant-session-access').inputValue(), 'none');
    await page.locator('#assistant-provider').selectOption('codex');
    assert(!(await page.locator('#assistant-mode option[value="ask"]').isDisabled()));
    assert.equal(await page.locator('.assistant-mode-note').innerText(), '');
    await page.locator('#assistant-provider').selectOption('claude');
    await page.locator('#assistant-mode').selectOption('ask');
    const send = async (prompt) => {
      await page.locator('#assistant-input').fill(prompt);
      await page.locator('#assistant-send').click();
      await page.locator('.assistant-approval:not(.resolved)').waitFor();
    };
    const done = () => page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Tur tamamlandı');
    await send('approval');
    const card = page.locator('.assistant-approval:not(.resolved)');
    assert((await page.locator('.assistant-status').innerText()).includes('Onayınız bekleniyor'));
    assert((await card.locator('.assistant-diff-removed').allTextContents()).join('').includes('initial = 1;'));
    assert((await card.locator('.assistant-diff-added').allTextContents()).join('').includes('approved = 42;'));
    assert((await page.locator('.cm-content').innerText()).includes('initial = 1;'));
    await card.getByRole('button', { name: 'İzin ver', exact: true }).focus();
    await page.keyboard.press('Enter');
    await done();
    await page.waitForFunction(() => document.querySelector('.cm-content').textContent.includes('approved = 42;'));
    assert.equal(fs.readFileSync(path.join(server.workspace, 'sample.m'), 'utf8'), 'approved = 42;\n');
    assert((await page.locator('.assistant-approval.resolved').innerText()).includes('İzin verildi:'));
    assert.equal(await page.locator('.assistant-approval.resolved button').count(), 0);
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await send('approval-twice');
    await card.getByRole('textbox', { name: 'Ret nedeni (isteğe bağlı)' }).fill('Dosyayı koru');
    await card.getByRole('button', { name: 'Reddet', exact: true }).click();
    // This fixture requests a second change; deny it too.
    await page.waitForFunction(() => document.querySelectorAll('.assistant-approval.resolved').length === 1 && document.querySelector('.assistant-approval:not(.resolved)'));
    await card.getByRole('button', { name: 'Reddet', exact: true }).click();
    await done();
    assert.equal(fs.readFileSync(path.join(server.workspace, 'sample.m'), 'utf8'), 'approved = 42;\n');
    assert((await page.locator('#assistant-transcript').innerText()).includes('Dosyayı koru'), await page.locator('#assistant-transcript').innerText());
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await send('approval-twice');
    await card.getByRole('button', { name: 'Bu görüşme için izin ver', exact: true }).click();
    await done();
    assert.equal(await page.locator('.assistant-approval').count(), 1);
    await page.waitForFunction(() => document.querySelector('.cm-content').textContent.includes('approved = 43;'));
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await send('approval');
    await page.locator('#assistant-stop').click();
    await page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Durduruldu');
    assert.equal(await page.locator('.assistant-approval:not(.resolved)').count(), 0);
    assert((await page.locator('.assistant-approval.resolved').innerText()).includes('Reddedildi:'));
    assert.equal(fs.readFileSync(path.join(server.workspace, 'sample.m'), 'utf8'), 'approved = 43;\n');
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await page.locator('#assistant-provider').selectOption('codex');
    await send('approval-command-write');
    assert((await card.innerText()).includes('Kabuk'));
    assert((await card.innerText()).includes('printf approved > sample.m'));
    assert(!(await card.locator('.assistant-approval-summary').innerText()).includes('/bin/zsh'));
    await card.getByRole('button', { name: 'İzin ver', exact: true }).click();
    await done();
    await page.waitForFunction(() => document.querySelector('.cm-content').textContent.includes('approved = 42;'));
    assert.equal(fs.readFileSync(path.join(server.workspace, 'sample.m'), 'utf8'), 'approved = 42;\n');
    await page.locator('#assistant-input').fill('hold');
    await page.locator('#assistant-send').click();
    await page.locator('#assistant-stop:not(:disabled)').waitFor();
    assert(!(await page.locator('#assistant-send').isDisabled()));
    await page.locator('#assistant-input').fill('steering message');
    await page.locator('#assistant-send').click();
    await page.waitForFunction(() => document.querySelector('#assistant-transcript').textContent.includes('Bu tur sırasında gönderildi'));
    await page.locator('#assistant-stop').click();
    await page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Durduruldu');
    // Persistence belongs to settings; reload re-reads the saved choice.
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await page.locator('#assistant-mode').selectOption('edit');
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('mf-settings-v1')).assistant.mode === 'edit');
    await page.reload();
    await page.locator('#assistant-panel').waitFor();
    assert.equal(await page.locator('#assistant-mode').inputValue(), 'edit');
    const freshContext = await browser.newContext({ locale: 'tr-TR' });
    const fresh = await freshContext.newPage();
    await fresh.goto(server.launch.url);
    await fresh.locator('#toggle-assistant').click();
    assert.equal(await fresh.locator('#assistant-mode').inputValue(), 'ask');
    console.log('UI ASSISTANT APPROVALS PASS: Turkish cards, diff, keyboard Allow, live tab refresh, Deny, conversation permission, Stop and defaults.');
  } finally {
    if (browser) await browser.close();
    await server.close();
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
