const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const { assistantServer } = require('./assistant_harness.cjs');
(async () => {
  const server = await assistantServer();
  let browser;
  try {
    browser = await chromium.launch({ headless: true });
    const context = await browser.newContext({ locale: 'tr-TR' });
    const page = await context.newPage();
    await page.goto(server.launch.url);
    await page.locator('#files .file-button').filter({ hasText: 'sample' }).waitFor();
    assert(await page.locator('#assistant-panel').isHidden(), 'panel is closed for fresh localStorage');
    await page.locator('#toggle-assistant').click();
    await page.locator('#assistant-panel').waitFor();
    await page.waitForFunction(() => [...document.querySelector('#assistant-provider').options].every((option) => !option.disabled));
    assert((await page.locator('.assistant-empty').innerText()).includes('Octave oturumunuza erişemez'));
    await page.locator('#files .file-button').filter({ hasText: 'sample' }).click();
    await page.locator('#editor .cm-line').first().click();
    await page.locator('#assistant-provider').selectOption('codex');
    assert.equal(await page.locator('#assistant-mode').inputValue(), 'ask');
    await page.locator('#assistant-mode').selectOption('read-only');
    await page.locator('#assistant-attach').check();
    assert((await page.locator('.assistant-attachment').innerText()).includes('sample.m'));
    await page.locator('#assistant-input').fill('hello');
    const sent = page.waitForRequest((request) => request.url().endsWith('/api/assistant/start'));
    await page.locator('#assistant-input').press('Enter');
    const request = (await sent).postDataJSON();
    assert.equal(request.context.path, 'sample.m');
    assert.equal(request.mode, 'read-only');
    assert(!Object.hasOwn(request.context, 'content'));
    await page.getByText('Fixture answer', { exact: true }).waitFor();
    await page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Tur tamamlandı');
    assert.equal(await page.locator('#assistant-transcript img').count(), 0, 'provider HTML never becomes an element');
    assert((await page.locator('#assistant-transcript details').count()) > 0);
    await page.getByRole('button', { name: 'Editöre ekle', exact: true }).click();
    assert((await page.locator('#editor .cm-content').innerText()).includes('x = 42;'));
    assert((await page.locator('.assistant-note').innerText()).includes('yalnızca yolu'));
    await page.locator('#assistant-unsaved').check();
    assert.equal(await page.locator('.assistant-note').innerText(), '');
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await page.locator('#assistant-provider').selectOption('claude');
    await page.locator('#assistant-input').fill('hello with draft');
    const draftSent = page.waitForRequest((request) => request.url().endsWith('/api/assistant/start'));
    await page.locator('#assistant-send').click();
    const draftRequest = (await draftSent).postDataJSON();
    assert(draftRequest.context.content.includes('x = 42;'));
    assert.equal(draftRequest.context.include_unsaved, true);
    await page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Tur tamamlandı');
    // An external edit reloads a clean tab and preserves a dirty one after a turn.
    fs.writeFileSync(path.join(server.workspace, 'sample.m'), 'external = 2;\n');
    await page.locator('#assistant-input').fill('refresh files');
    await page.locator('#assistant-input').press('Enter');
    await page.locator('#tabs .assistant-disk-note').waitFor();
    assert((await page.locator('#editor .cm-content').innerText()).includes('x = 42;'), 'dirty draft is preserved');
    assert.equal(await page.locator('#tabs .assistant-disk-note').innerText(), 'Diskte değişti');
    await page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Tur tamamlandı');
    await page.getByRole('button', { name: 'Yeni görüşme', exact: true }).click();
    await page.locator('#assistant-attach').uncheck();
    await page.locator('#assistant-provider').selectOption('agy');
    await page.locator('#assistant-input').fill('wait');
    await page.locator('#assistant-send').click();
    await page.locator('#assistant-stop:not(:disabled)').waitFor();
    assert.equal(await page.locator('.assistant-status').innerText(), 'Çalışıyor…');
    await page.locator('#assistant-stop').click();
    await page.waitForFunction(() => document.querySelector('.assistant-status').textContent === 'Durduruldu');
    await page.locator('#assistant-divider').focus();
    await page.locator('#assistant-divider').press('ArrowLeft');
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('mf-settings-v1')).assistant.width === 350);
    await page.locator('#assistant-panel').getByRole('button', { name: 'Kapat', exact: true }).click();
    assert(await page.locator('#assistant-panel').isHidden());
    await page.locator('#editor .cm-line').first().click();
    await page.keyboard.press('ControlOrMeta+Shift+A');
    await page.locator('#assistant-panel').waitFor();
    await page.waitForFunction(() => JSON.parse(localStorage.getItem('mf-settings-v1')).assistant.open);
    await page.reload();
    await page.locator('#assistant-panel').waitFor();
    assert.equal(await page.locator('#assistant-panel').evaluate((node) => node.style.width), '350px');
    console.log('UI ASSISTANT PASS: Turkish panel, providers, streaming, attachments, code insertion, dirty preservation, stop, shortcut, persisted layout.');
  } finally {
    if (browser) await browser.close();
    await server.close();
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
