const {chromium}=require('@playwright/test');
const fs=require('fs'),path=require('path'),assert=require('assert');
const {randomUUID}=require('node:crypto');

(async()=>{
 const launch=JSON.parse(fs.readFileSync('.matlab-free/launch.json','utf8'));
 const [base,token]=launch.url.split('#');
 const request=(route,body)=>fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'X-MF-Token':token,...body===undefined?{}:{'Content-Type':'application/json'}},body:body===undefined?undefined:JSON.stringify(body)});
 const waitIdle=async()=>{for(let index=0;index<200;index++){let state=await (await request('api/state')).json();if(state.status==='idle')return state;await new Promise(resolve=>setTimeout(resolve,50));}throw new Error('Octave job timeout');};
 const initial=await waitIdle();
 const marker='ui-file-ops-'+randomUUID();
 const root=path.join(initial.workspace,marker);
 const target=path.join(root,'hedef');
 const original='ilk.m',clean='temiz.m',dirty='kirli.m',copy='kopya.m';
 let trashPath='';
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({ locale: "tr-TR",viewport:{width:1512,height:982}});
 const errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.goto(launch.url);
  await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
  await page.locator('[data-file-operation="create_folder"]').first().click();
  await page.getByLabel('Klasör adı').fill(marker);
  await page.locator('.file-operation-dialog button').click();
  await page.waitForFunction(name=>[...document.querySelectorAll('.file-button.folder')].some(button=>button.textContent.includes(name)),marker);
  assert.equal(await page.locator('.file-button.selected').filter({hasText:marker}).count(),1);
  await page.locator('.file-button.folder').filter({hasText:marker}).click();
  await page.waitForFunction(folder=>document.querySelector('#folder-address').title===folder,root);
  await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
  await page.locator('[data-file-operation="create_folder"]').first().click();
  await page.getByLabel('Klasör adı').fill('hedef');
  await page.locator('.file-operation-dialog button').click();
  await page.waitForFunction(()=>[...document.querySelectorAll('.file-button.folder')].some(button=>button.textContent.includes('hedef')));
  await page.locator('[data-file-operation="create_file"]').first().click();
  await page.getByLabel('Dosya adı').fill(original);
  await page.locator('.file-operation-dialog button').click();
  await page.waitForFunction(name=>document.querySelector('#editor-label').textContent===name,original);
  // Finding 1: a clean open tab must not acquire an external writer's hash.
  fs.writeFileSync(path.join(root,original),'external B');
  await page.getByRole('button',{name:original,exact:true}).click({button:'right'});
  await page.locator('#file-context-menu [data-file-operation="rename"]').click();
  await page.getByLabel('Yeni ad').fill('blocked.m');
  let rejected=page.waitForResponse(response=>response.url().endsWith('/api/file-operation')&&response.request().postDataJSON()?.operation==='rename');
  await page.locator('.file-operation-dialog button').click();
  assert.equal((await rejected).status(),409);
  assert.equal(await page.locator('#editor-label').innerText(),original);
  assert.equal(fs.readFileSync(path.join(root,original),'utf8'),'external B');
  assert(!fs.existsSync(path.join(root,'blocked.m')));
  fs.writeFileSync(path.join(root,original),'');
  let row=page.getByRole('button',{name:original,exact:true});
  await row.focus();
  await row.press('Enter');
  await page.getByLabel('Yeni ad').fill(clean);
  await page.locator('.file-operation-dialog button').click();
  await page.waitForFunction(name=>document.querySelector('#editor-label').textContent===name,clean);
  assert.equal(await page.locator('.file-button.selected').filter({hasText:clean}).count(),1);
  assert(!fs.existsSync(path.join(root,original)));assert(fs.existsSync(path.join(root,clean)));
  await page.locator('.cm-content').fill('dirty_value = 42;\n');
  await page.waitForFunction(()=>document.querySelector('#save-state').textContent.includes('Kaydedilmemiş'));
  // Same conflict with an unsaved buffer: failed move keeps buffer and disk B.
  fs.writeFileSync(path.join(root,clean),'external dirty B');
  await page.getByRole('button',{name:clean,exact:true}).click({button:'right'});
  await page.locator('#file-context-menu [data-file-operation="move"]').click();
  await page.getByLabel('Hedef klasör').fill(target);
  rejected=page.waitForResponse(response=>response.url().endsWith('/api/file-operation')&&response.request().postDataJSON()?.operation==='move');
  await page.locator('.file-operation-dialog button').click();
  assert.equal((await rejected).status(),409);
  assert((await page.locator('.cm-content').innerText()).includes('dirty_value = 42;'));
  assert.equal(fs.readFileSync(path.join(root,clean),'utf8'),'external dirty B');
  const saveConflict=page.waitForResponse(response=>response.url().endsWith('/api/file')&&response.request().method()==='POST');
  await page.locator('[data-action="save"]').first().click();
  assert.equal((await saveConflict).status(),409);
  assert.equal(fs.readFileSync(path.join(root,clean),'utf8'),'external dirty B');
  fs.writeFileSync(path.join(root,clean),'');
  await page.getByRole('button',{name:clean,exact:true}).click({button:'right'});
  await page.locator('#file-context-menu [data-file-operation="rename"]').click();
  await page.getByLabel('Yeni ad').fill(dirty);
  await page.locator('.file-operation-dialog button').click();
  await page.waitForFunction(name=>document.querySelector('#editor-label').textContent===name,dirty);
  assert((await page.locator('.cm-content').innerText()).includes('dirty_value = 42;'));
  assert((await page.locator('#save-state').innerText()).includes('Kaydedilmemiş'));
  await page.waitForTimeout(300);
  let draft=await page.evaluate(()=>JSON.parse(localStorage.getItem('mf-drafts-v2')));
  let tabs=Object.values(draft.scopes).flatMap(scope=>scope.tabs);
  assert(tabs.some(tab=>tab.path.endsWith('/'+dirty)&&tab.dirty));assert(!tabs.some(tab=>tab.path.endsWith('/'+clean)));
  await page.locator('#file-ops-toolbar [data-file-operation="duplicate"]').click();
  await page.getByLabel('Kopya adı').fill(copy);
  await page.locator('.file-operation-dialog button').click();
  await page.waitForFunction(name=>[...document.querySelectorAll('.file-button')].some(button=>button.textContent.includes(name)),copy);
  assert.equal(await page.locator('.file-button.selected').filter({hasText:copy}).count(),1);assert(fs.existsSync(path.join(root,copy)));
  await page.getByRole('button',{name:dirty,exact:true}).click({button:'right'});
  await page.locator('#file-context-menu [data-file-operation="move"]').click();
  await page.getByLabel('Hedef klasör').fill(target);
  const movedResponse=page.waitForResponse(response=>response.url().endsWith('/api/file-operation')&&response.request().postDataJSON()?.operation==='move');
  await page.locator('.file-operation-dialog button').click();
  assert.equal((await movedResponse).status(),200);
  await page.waitForFunction(name=>document.querySelector('#editor-label').textContent===name,dirty);
  assert(fs.existsSync(path.join(target,dirty)));assert(!fs.existsSync(path.join(root,dirty)));
  await page.waitForTimeout(300);
  draft=await page.evaluate(()=>JSON.parse(localStorage.getItem('mf-drafts-v2')));
  tabs=Object.values(draft.scopes).flatMap(scope=>scope.tabs);
  assert(tabs.some(tab=>tab.path===path.join(target,dirty)&&tab.dirty));
  await page.locator('.file-button.folder').filter({hasText:'hedef'}).click();
  await page.waitForFunction(folder=>document.querySelector('#folder-address').title===folder,target);
  await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
  row=page.getByRole('button',{name:dirty,exact:true});
  await row.focus();
  page.once('dialog',dialog=>dialog.accept());
  const trashResponse=page.waitForResponse(response=>response.url().endsWith('/api/file-operation')&&response.request().postDataJSON()?.operation==='trash');
  await row.press('Meta+Backspace');
  const response=await trashResponse;
  assert.equal(response.status(),200);
  trashPath=(await response.json()).path;
  await page.waitForFunction(name=>![...document.querySelectorAll('.file-button')].some(button=>button.textContent.includes(name)),dirty);
  assert((await page.locator('#save-state').innerText()).includes('Kaydedilmemiş'));
  assert((await page.locator('.cm-content').innerText()).includes('dirty_value = 42;'));
  assert.equal(await page.locator('#editor-label').innerText(),dirty);
  assert(fs.existsSync(trashPath));assert(!fs.existsSync(path.join(target,dirty)));
  await page.locator('#folder-up').click();
  await page.waitForFunction(folder=>document.querySelector('#folder-address').title===folder,root);
  await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
  await page.locator('#folder-up').click();
  await page.waitForFunction(folder=>document.querySelector('#folder-address').title===folder,initial.workspace);
  await page.waitForFunction(()=>document.querySelector('#status-text').textContent==='Hazır');
  assert.deepStrictEqual(errors,[]);
  console.log('UI FILE OPS PASS: create, clean/dirty rename, draft path migration, duplicate, move, Trash confirmation, refresh and selection.');
 }finally{
  try{let state=await (await request('api/state')).json();if(state.cwd!==initial.workspace){await request('api/folder',{path:initial.workspace});await waitIdle();}}catch{}
  await browser.close();
  if(trashPath)fs.rmSync(trashPath,{recursive:true,force:true});
  fs.rmSync(root,{recursive:true,force:true});
 }
})().catch(error=>{console.error(error);process.exit(1);});
