const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

(async () => {
  const launch = JSON.parse(fs.readFileSync('.matlab-free/launch.json', 'utf8'));
  const file = path.resolve('workspace/source_files_ui_entry.m');
  const original = 'r="ab"+"cd";';
  fs.writeFileSync(file, original);
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ locale: 'tr-TR', viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  const errors = [], requests = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('request', (request) => { if (request.url().endsWith('/api/execute')) requests.push(request.postDataJSON()); });
  const idle = () => page.waitForFunction(() => document.querySelector('#status-text')?.textContent === 'Hazır');
  const editor = page.locator('.cm-content');
  const run = async () => {
    const response = page.waitForResponse((reply) => reply.url().endsWith('/api/execute') && reply.request().method() === 'POST');
    await editor.press('F5');
    const reply = await response;
    assert.equal(reply.status(), 202);
    const accepted = await reply.json();
    await expect(page.locator(`.console-entry[data-job="${accepted.job}"] .console-time`)).toHaveText(/\d+(?:\.\d+)? s/);
    await idle();
    return accepted;
  };
  try {
    await page.goto(launch.url);
    await idle();
    await page.locator('#files').getByRole('button', { name: 'source_files_ui_entry.m', exact: true }).click();
    await expect(page.locator('#editor-label')).toHaveAttribute('title', file);
    await expect(editor).toHaveText(original);
    await run();
    assert.deepEqual(requests.at(-1), { code: '', mode: 'file', argument: file, history: false });
    await expect(page.locator('.source-adapter-note')).toHaveCount(0);
    await page.locator('#settings').click();
    const setting = page.getByRole('checkbox', { name: 'Kayıtlı giriş betiklerindeki çift tırnaklı metinleri uyarla' });
    await expect(setting).not.toBeChecked();
    await expect(page.locator('.settings-note')).toHaveCount(1);
    await expect(page.locator('.file-source-settings-note')).toContainText('mfilename ve yığın yolları');
    await setting.check();
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('mf-settings-v1')).preferences.adaptFileLiterals)).toBe(true);
    await page.locator('#modal-close').click();
    await page.reload();
    await idle();
    await page.locator('#settings').click();
    await expect(setting).toBeChecked();
    await page.locator('#modal-close').click();
    await page.locator('#files').getByRole('button', { name: 'source_files_ui_entry.m', exact: true }).click();
    await expect(page.locator('#editor-label')).toHaveAttribute('title', file);
    await expect(editor).toHaveText(original);
    const failing = 'r="saved snapshot";\nmissing_saved_ui;';
    await editor.fill(failing);
    const accepted = await run();
    assert.equal(requests.at(-1).adapt_file_literals, true);
    assert.equal(requests.at(-1).file_hash, crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'));
    assert.equal(requests.at(-1).source_context, undefined);
    assert.equal(requests.at(-1).adapt_editor_literals, undefined);
    assert.equal(fs.readFileSync(file, 'utf8'), failing);
    assert.equal(accepted.source_context.document, failing);
    const entry = page.locator(`.console-entry[data-job="${accepted.job}"]`);
    await expect(entry.locator('.console-source')).toHaveText(failing);
    await expect(entry.locator('.source-adapter-note')).toContainText('Uyarlandı:');
    const link = entry.locator('.source-error-location').first();
    await expect(link).toHaveAttribute('data-line', '2');
    await link.click();
    await expect(page.locator('#cursor')).toContainText('Satır 2');
    await editor.fill('r="dirty after submission";');
    await link.click();
    await expect(page.locator('.source-snapshot')).toHaveValue(failing);
    await expect(page.locator('.source-snapshot')).toHaveAttribute('readonly', '');
    await page.locator('#modal-close').click();
    // Historical errors keep the server snapshot after another native command.
    await page.locator('#command').fill('native_console_literal="native";');
    const nativeResponse = page.waitForResponse((reply) => reply.url().endsWith('/api/execute'));
    await page.locator('#command').press('Enter');
    await nativeResponse;
    await idle();
    assert.equal(requests.at(-1).adapt_file_literals, undefined);
    await link.click();
    await expect(page.locator('.source-snapshot')).toHaveValue(failing);
    await page.locator('#modal-close').click();
    await page.locator('#settings').click();
    await setting.uncheck();
    await page.locator('#modal-close').click();
    await editor.fill(original);
    await run();
    assert.equal(requests.at(-1).adapt_file_literals, undefined);
    assert.equal(requests.at(-1).file_hash, undefined);
    await expect(page.locator('#clear-console')).toBeVisible();
    assert.deepEqual(errors, []);
    console.log('UI SOURCE FILES PASS: default F5, explicit opt-in persistence, dirty save/hash, unique settings notes, exact/historical snapshot links and disabled payload.');
  } finally {
    await context.close();
    await browser.close();
    fs.rmSync(file, { force: true });
  }
})().catch((error) => { console.error(error); process.exit(1); });
